# Generated by scripts/bump-brew-formula.mjs — do not edit by hand.
class GrowtherC5 < Formula
  desc "Growther.si C5 — self-contained V8-bytecode agent runtime"
  homepage "https://growther.si"
  version "2026.10.10-v324"

  on_macos do
    depends_on macos: :ventura
    if Hardware::CPU.arm?
      url "https://raw.githubusercontent.com/GrowtherSI/release/main/dist/c5/v2026.10.10-v324/growther-c5-macos-arm64-node24.tar.gz"
      sha256 "4e9f2459fe35b5db3b07c413513b55e24321391ec54e928dfa7d5b0b8d51cd74"
    end
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/GrowtherSI/release/main/dist/c5/v2026.10.10-v324/growther-c5-macos-x64-node24.tar.gz"
      sha256 "cf91c4543fda1d8a668878a5416ccbcd4f9e455f730fd986276ec9320ebaad3d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/GrowtherSI/release/main/dist/c5/v2026.10.10-v324/growther-c5-linux-x64-node24.tar.gz"
      sha256 "5af1df0028eea2fda627edd025e6af36d86999a3e78d56aa55b703e4afa544db"
    end
  end

  def install
    # Keep the binary and its signed build_manifest.json together in libexec and
    # symlink the binary into bin: process.execPath resolves the symlink, so the
    # manifest is found via the adjacent (Zero-Install) attestation path.
    binary = Dir["growther-*"].reject { |f| f.end_with?(".json") }.first
    libexec.install binary => "growther"
    libexec.install "build_manifest.json" if File.exist?("build_manifest.json")
    bin.install_symlink libexec/"growther"
  end

  test do
    system "#{bin}/growther", "version"
  end
end
