# Generated by scripts/bump-brew-formula.mjs — do not edit by hand.
class GrowtherC5 < Formula
  desc "Growther.si C5 — self-contained V8-bytecode agent runtime"
  homepage "https://growther.si"
  version "2026.10.7-v322"

  on_macos do
    depends_on macos: :ventura
    if Hardware::CPU.arm?
      url "https://raw.githubusercontent.com/GrowtherSI/release/main/dist/c5/v2026.10.7-v322/growther-c5-macos-arm64-node24.tar.gz"
      sha256 "90a515b29f807f395c5d37113168a6925690d6ac89693cbefe241da8a16efbe0"
    end
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/GrowtherSI/release/main/dist/c5/v2026.10.7-v322/growther-c5-macos-x64-node24.tar.gz"
      sha256 "ba40c4b0bc45836bf12ec379801bea1815b35342c020ccea06f0c60b2597348c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/GrowtherSI/release/main/dist/c5/v2026.10.7-v322/growther-c5-linux-x64-node24.tar.gz"
      sha256 "f1e94fda018bce2090998ff0f1cde373952f51c10def49661c29f19722038c3a"
    end
  end

  def install
    # Keep the binary and its signed build_manifest.json together in libexec and
    # symlink the binary into bin: process.execPath resolves the symlink, so the
    # manifest is found via the adjacent (Zero-Install) attestation path.
    binary = Dir["growther-*"].reject { |f| f.end_with?(".json") }.first
    libexec.install binary => "growther"
    libexec.install "build_manifest.json" if File.exist?("build_manifest.json")
    bin.install_symlink libexec/"growther"
  end

  test do
    system "#{bin}/growther", "version"
  end
end
